name: CI

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Download
        run: bash scripts/download.sh
      - name: Patch
        run: bash scripts/patch.sh
      - name: Install
        run: bash scripts/install.sh
      - name: Build
        run: bash scripts/build.sh
      - name: Archive
        run: bash scripts/archive.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: resources
          path: resources.tar.gz
      - uses: ncipollo/release-action@v1
        name: Release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "resources.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
